name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_and_rollback_on_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, pdo, bcmath, json, tokenizer, xml

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Enable Maintenance Mode on Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USERNAME }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/laravel-docker
            echo "Current PATH: $PATH"
            php -v
            php artisan down
        env:
          SSH_AUTH_SOCK: /dev/null

      - name: Deploy Code on Server 2
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.SERVER2_USERNAME }}
          password: ${{ secrets.SERVER2_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/laravel-docker
            echo "Current PATH: $PATH"
            
            # Run your deployment script here
            ./deploy.sh
            
            # If deployment is successful, set the output variable to 'true', otherwise 'false'
            if [ $? -eq 0 ]; then
              echo "::set-output name=deployment-successful::true"
            else
              echo "::set-output name=deployment-successful::false"
            fi
        env:
          SSH_AUTH_SOCK: /dev/null

      - name: Disable Maintenance Mode on Server 1 and Rollback on Deployment Failure
        if: steps.deploy.outputs.deployment-successful == 'false'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USERNAME }}
          password: ${{ secrets.SERVER1_PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/laravel-docker
            echo "Current PATH: $PATH"
            php -v
            php artisan up
            
            # Rollback deployment on Server 2 (optional)
            sshpass -p "${{ secrets.SERVER2_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 "${{ secrets.SERVER2_USERNAME }}@${{ secrets.SERVER2_HOST }}" "cd /var/www/html/laravel-docker && ./rollback.sh"
        env:
          SSH_AUTH_SOCK: /dev/null
